# SPDX-License-Identifier: GPL-2.0
dts-dirs += exynos

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_GLOBAL) := \
	exynos/exynos7885-jackpotlte_eur_open_07.dtb \
	exynos/exynos7885-jackpotlte_can_open_07.dtb \
	exynos/exynos7885-jackpotlte_kor_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_JNP) := \
        exynos/exynos7885-jackpotlte_jpn_dcm_00.dtb \
        exynos/exynos7885-jackpotlte_jpn_dcm_03.dtb \

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOT2LTE_GLOBAL) := \
	exynos/exynos7885-jackpot2lte_eur_open_07.dtb

always         := $(dtb-y)
clean-files    := *.dtb
